# Generated by Django 3.2.5 on 2021-07-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submition_date',
            new_name='submission_date',
        ),
    ]
