# Generated by Django 3.2.5 on 2021-07-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_rename_submition_date_pet_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vacccination',
            new_name='vacccinations',
        ),
    ]
